/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package toernooileider;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;




/**
 *
 * @author jannedevos
 */
public class ToernooiPanel extends javax.swing.JPanel {
    
    private static int berEvenementID;
    private ToernooiLeiderView toernooi;

    
    /**
     * Creates new form ToernooiPanel
     */
    public ToernooiPanel() {
        initComponents();
        getToernooien();
        
    }
    
    public ToernooiPanel(ToernooiLeiderView toernooi) {
        initComponents();
        getToernooien();
        this.toernooi = toernooi;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selecteerBut = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        toernooiTable = new javax.swing.JTable();

        selecteerBut.setText("Selecteren");
        selecteerBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selecteerButMouseClicked(evt);
            }
        });

        toernooiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        toernooiTable.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                toernooiTableComponentAdded(evt);
            }
        });
        jScrollPane1.setViewportView(toernooiTable);
        toernooiTable.getAccessibleContext().setAccessibleName("ToernooiTable");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selecteerBut)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selecteerBut)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

  
    public int getEvenementID()
    {
        return berEvenementID;
    }
    
    private void selecteerButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecteerButMouseClicked
        int[] row = toernooiTable.getSelectedRows();
        if (row.length == 0)
        {
            JOptionPane.showMessageDialog(this, "Geen toernooi geselecteerd!", "Fout", JOptionPane.PLAIN_MESSAGE);
        }
        else if (row.length == 1)
        {
            int ID;
            ID = Integer.parseInt(toernooiTable.getValueAt(row[0], 0).toString());
            toernooi.setEvenementID(ID);
            
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Selecteer 1 toernooi!", "Fout", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_selecteerButMouseClicked

    private void toernooiTableComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_toernooiTableComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_toernooiTableComponentAdded

    private void getToernooien () {
        String query = "SELECT  Evenement.evenementID, Evenement.datum, Evenement.locatieID, Evenement.naam, ToernooiSoort.beschrijving "
                + "FROM Evenement "
                + "INNER JOIN  Toernooi ON Evenement.evenementID = Toernooi.evenementID "
                + "JOIN ToernooiSoort ON Toernooi.soortToernooi = ToernooiSoort.soortID "
                + "ORDER BY Evenement.datum ASC;";
        try {
            Connection conn = SimpleDataSource.getConnection();
            PreparedStatement stat = conn.prepareStatement(query);
            ResultSet result = stat.executeQuery();
            fillTable(result);
            result.close();
            stat.close();
        }
        catch (Exception e) {
            //FullHouse.showDBError(e);
            System.out.println(e);
        }
    }
        
        
        private void fillTable(ResultSet result) throws SQLException {
            String[] columnNames = {"ID", "Evenement naam", "Soort", "Locatie", "Datum"};
            DefaultTableModel model = new DefaultTableModel();
            model.setDataVector(new Object[][]{}, columnNames);
            while (result.next()) {
            String ID = result.getString("evenementID");
            Date datum = result.getDate("datum");
            int locatie = result.getInt("locatieID");
            String naam = result.getString("naam");
            String soort = result.getString("beschrijving");
            Object[] rowData = {ID, naam, soort, locatie, datum};
            model.addRow(rowData);
            }
        toernooiTable.setModel(model);
        result.close();
        
    }
    
        
  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton selecteerBut;
    private javax.swing.JTable toernooiTable;
    // End of variables declaration//GEN-END:variables
}
